repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files

-   repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]

-   repo: https://github.com/pycqa/isort
    rev: 6.0.0  # Updated to match pyproject.toml version
    hooks:
    -   id: isort
        args: [--profile, black]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy
        exclude: ^tests/
        additional_dependencies: [types-PyYAML]

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: poetry run pytest --cov=kreatisite
        language: system
        pass_filenames: false
        always_run: true
