[tool.poetry]
name = "kreatisite"
version = "0.1.0"
description = "KreatiSite command line application"
authors = ["DevixLabs <info@devixlabs.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
flake8 = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
kreatisite = "kreatisite.cli:main"
lint = "kreatisite.scripts:lint"
test = "kreatisite.scripts:test"
check = "kreatisite.scripts:check_all"
